name: Node.js + ngrok

on: [push]

jobs:
  serve:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Start server in background
        run: |
          nohup npm start &
          sleep 5

      - name: Install ngrok
        run: npm install -g ngrok

      - name: Start ngrok
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
          ngrok http 3000 > ngrok.log &
          sleep 10
          curl http://127.0.0.1:4040/api/tunnels > tunnels.json
          cat tunnels.json

      - name: Show ngrok URL
        run: |
          echo "🌐 Public URL:"
          cat tunnels.json | grep -o 'https://[0-9a-zA-Z.-]*.ngrok-free.app'
