name: CI/CD Node.js

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Deploy to Vercel
        run: vercel --token=${{ 2yaY20JV5LG2iH4WAkOFMMXVfS1_dF2xbpDig1oqgqmRzCe6 }} --prod --confirm
